---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gowebapi
  namespace: developpement
spec:
  selector:
    matchLabels:
      app: gowebapi
  replicas: 2
  template:
    metadata:
      labels:
        app: gowebapi
    spec:
      containers:
      - name: gowebapi
        image: efrei2023/golangwebapi:latest
        ports:
        - containerPort: 8181
...
---
apiVersion: v1
kind: Service
metadata:
  name: gowebapi
  namespace: developpement
spec:
  selector:
    type: NodePort
    app: gowebapi
  ports:
    - protocol: TCP
      port: 8181
      targetPort: 8181
      NodePort: 31280
