---
apiVersion: v1
kind: Namespace
metadata:
  name: developpement
  labels:
    name: developpement
...

---
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    name: production
...

