---
apiVersion: v1
kind: Namespace
metadata:
  name: developpement
  labels:
    environment: developpement
---
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    environment: production
...
